name: build

on:
  pull_request:
    paths:
      - 'build-web.sh'
      - 'prepare-resvg.sh'
      - '.github/workflows/build-web.yml'

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7.0.1

      - name: build
        run: |
          . ./prepare-resvg.sh
          ./build-web.sh
