name: release

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install resvg
        run: |
          sudo apt-get -y update
          sudo apt-get install -y resvg
          # I hate Ubuntu https://packages.ubuntu.com/jammy/amd64/resvg/filelist
          mkdir bin
          ln -s /usr/bin/rendersvg ./bin/resvg

      - name: build
        run: |
          PATH="./bin/:$PATH" ./build.sh

      - name: pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: "target/*"

      - name: tagged-release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: "target/*"

