name: release

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Install resvg
        run: |
          # Why Ubuntu uses legacy version of resvg?

          mkdir bin
          cd bin

          # depName=RazrFalcon/resvg
          RESVG_VERSION="v0.41.0"

          wget "https://github.com/RazrFalcon/resvg/releases/download/${RESVG_VERSION}/resvg-linux-x86_64.tar.gz"
          tar xf resvg-linux-x86_64.tar.gz

          cd ..


      - name: build
        run: |
          PATH="./bin/:$PATH" ./build.sh

      - name: pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            target/*
            resources.tar

      - name: tagged-release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            target/*
            resources.tar

